### ISSUE TITLE
Doesn't work with ido-next-match

### ISSUE THREAD

**Issue by andyleejordan** [larkery/ido-grid-mode.el#5]
Hi Tom,

This package does exactly what I want: gives a much better ido view, but is not ido-vertical (which gets unbearably slow with many candidates), but unfortunately, it doesn't work with `ido-next-match` (usually bound to C-s).

I reproduced this with an `emacs -q` session of GNU Emacs 24.5.50.1, where I manually enabled `ido-mode`, loaded `ido-grid-mod.el`, and enabled `ido-grid-mode` (so, no other packages or settings).

I expect `C-s` (bound to `ido-next-match` to move to the next match in an `ido` session, but `ido-grid-mode` does nothing. I verified that `ido-grid-mode-keys` is not interfering, and double-checked that `C-s` was bound when in `ido-grid`.

Thanks,

Andy

**Comment by larkery** [comment]
Glad you find it useful.. The way the grid works means ido-next-match is ineffective; however you can bind the key you want to ido-grid-mode-next to move the cursor to the next thing.

I'm on holiday without a computer for a few days so I won't be sorting this out until I get home, but I'll add C-s and presumably C-r to the standard key bindings then. If you'd like to do it yourself look at the setup hook somewhere near the bottom of the file.

Tom

On 4 November 2015 07:46:14 CET, Andy Schwartzmeyer notifications@github.com wrote:

> Hi Tom,
> 
> This package does exactly what I want: gives a much better ido view,
> but is not ido-vertical (which gets unbearably slow with many
> candidates), but unfortunately, it doesn't work with `ido-next-match`
> (usually bound to C-s).
> 
> I reproduced this with an `emacs -q` session of GNU Emacs 24.5.50.1,
> where I manually enabled `ido-mode`, loaded `ido-grid-mod.el`, and
> enabled `ido-grid-mode` (so, no other packages or settings).
> 
> I expect `C-s` (bound to `ido-next-match` to move to the next match in
> an `ido` session, but `ido-grid-mode` does nothing. I verified that
> `ido-grid-mode-keys` is not interfering, and double-checked that `C-s`
> was bound when in `ido-grid`.
> 
> Thanks,
> 
> Andy
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/larkery/ido-grid-mode.el/issues/5

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by larkery** [comment]
I have made this change - once MELPA catches up you should find these bindings work. If you have customized the bound keys you will need to `M-x customize-group ido-grid-mode` and then tick the boxes for them.

**Comment by andyleejordan** [comment]
Even on holiday you are faster than me! I was going to look into it myself. Thanks for the fix @larkery!

**Comment by andyleejordan** [comment]
Hey I reenabled ido-grid-mode and the change has made it's way into the package. It's exactly what I needed, thank you again! :octocat:

My use case is that a _lot_ of my matches have really similar names, to the point that I can't narrow with more characters and just need to move the selected match slightly.

@larkery When you say ido-grid makes ido-next-match ineffective, is there a better way I can do this?

**Comment by larkery** [comment]
Ah, I don't meant to say that it supersedes it in some way, just that it breaks it! The issue is that `ido-next-match` operates on `ido-matches` (via `ido-cur-list` and `ido-set-matches-1`), so if you have

```
A B C D
```

`ido-next-match` changes `ido-matches` to be

```
B C D A
```

However, the grid actually displays a copy of `ido-matches` called `ido-grid-mode-rotated-matches`. This is for compatibility with flx-ido which resets the contents of `ido-matches` frequently. To keep the position in the grid right it displays the copied list and ignores rotations of the original.

Practical upshot is, `ido-next-match` and `ido-prev-match` do not work, but `ido-grid-mode-next` and `ido-grid-mode-previous` are suitable replacements.

I don't know of a better way of picking between similar alternatives; some sort of thing like (avy)[https://github.com/abo-abo/avy] would be kind of neat; it would not be too hard to add labels to the things in ido-grid-mode and then temporarily alter the keymap to select them from keypresses.

**Comment by larkery** [comment]
If you try the latest master and customize `ido-grid-mode-jump` you might find it helps. I am trying it out at the moment; it adds bindings so keys `C-1,2,3..0` select item 1..10 quickly. if you set it to `label` then it will mark the first 10 things with a number.
